{
 "title": "Gateway API Comparison",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory (Data Plane)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"envoy-gateway-system\",container=\"\",pod=~\"envoy-envoy-envoy-gateway.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"kgateway\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"istio\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"kube-system\",container=\"\",pod=~\"(^cilium-.....$|cilium-envoy-.*)\"})",
     "legendFormat": "cilium (Envoy + Agent)"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"traefik-system\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"kong-system\",container=\"\",pod=~\"kong-controller-.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"nginx-system\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU (Data Plane)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"envoy-gateway-system\",container=\"\",pod=~\"envoy-envoy-envoy-gateway.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"kgateway\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"istio\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{namespace=\"kube-system\",container=\"\",pod=~\"(^cilium-.....$|cilium-envoy-.*)\"}[$__rate_interval]))",
     "legendFormat": "cilium (Envoy + Agent)"
    },
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"traefik-system\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"kong-system\",container=\"\",pod=~\"kong-controller-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"nginx-system\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (Control Plane)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"envoy-gateway-system\",container=\"\",pod=~\"^envoy-gateway-.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"kgateway-system\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"istio-system\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"kube-system\",container=\"\",pod=~\"cilium-operator-.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"traefik-system\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"kong-system\",container=\"\",pod=~\"kong-controller-.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"nginx-system\",container=\"\",pod=~\".*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU (Control Plane)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"envoy-gateway-system\",container=\"\",pod=~\"^envoy-gateway-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kgateway-system\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"istio-system\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kube-system\",container=\"\",pod=~\"cilium-operator-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"traefik-system\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kong-system\",container=\"\",pod=~\"kong-controller-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"nginx-system\",container=\"\",pod=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Scenarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Attached Routes Test",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{gateway!=\"\",test=\"attachedroutes\"}",
     "maxLines": 999999
    }
   ]
  },
  {
   "title": "Probe Test",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "{gateway!=\"\",test=\"probe\"}",
     "maxLines": 999999
    }
   ]
  }
 ]
}